b: test2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
        lease-renewal-interval-in-seconds: 0

spring:
  application:
    name: BookService
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarySystemDB

sleuth:
  sampler:
    probability: 1
