
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
        lease-renewal-interval-in-seconds: 0

spring:
  application:
    name: BookQueryService
  zipkin:
    base-url: http://localhost:9411/
    
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarySystemDB

sleuth:
  sampler:
    probability: 1
